version: '3.6'

networks:
  protected:
    driver: bridge
    internal: true
  connected:
    driver: bridge
    internal: true
  exposed:
    driver: bridge

volumes:
{%- if cookiecutter.use_sql in ["yes", "y"] %}
  db-data-pg:
    driver: local
{%- endif %}
{%- if cookiecutter.use_nosql in ["yes", "y"] %}
  db-data-mongo:
    driver: local
{%- endif %}
  static-data:
    driver: local
  media-data:
    driver: local
  certbot-conf:
    driver: local
  certbot-www:
    driver: local

services:
  app:
    build:
      context: ./{{ cookiecutter.app_path }}
    depends_on:
      {%- if cookiecutter.use_sql in ["yes", "y"] %}
      - db-pg
      {%- endif %}
      {%- if cookiecutter.use_nosql in ["yes", "y"] %}
      - db-mongo
      {%- endif %}
      {%- if cookiecutter.use_async_tasks %}
      - queue
      {%- endif %}
    env_file:
    - ./envfile
    networks:
    - protected
    - connected
    volumes:
    - media-data:/home/nonroot/code/media
{%- if cookiecutter.use_sql in ["yes", "y"] %}
  db-pg:
    networks:
    - protected
    image: postgres:10
    volumes:
    - db-data-pg:/var/lib/postgresql/data/
{%- endif %}
{%- if cookiecutter.use_nosql in ["yes", "y"] %}
  db-mongo:
    networks:
    - protected
    image: mongo:4
    volumes:
    - db-data-mongo:/data/db
{%- endif %}
{%- if cookiecutter.use_async_tasks %}
  queue:
    networks:
    - protected
    image: redis:5
{%- endif %}
  server:
    build:
      context: ./server
    depends_on:
    - app
    env_file:
    - ./envfile
    networks:
    - connected
    - exposed
    volumes:
    - static-data:/var/static
    - media-data:/var/media
