version: '3.6'

{%- set uses_cockroachdb = cookiecutter.use_sql_cockroachdb in ('y', 'yes') -%}
{%- set uses_postgres = cookiecutter.use_sql_postgres in ('y', 'yes') -%}
{%- set uses_mysql = cookiecutter.use_sql_mysql in ('y', 'yes') -%}
{%- set uses_mongodb = cookiecutter.use_nosql_mongodb in ('y', 'yes') -%}
{%- set uses_redis = cookiecutter.use_redis in ('y', 'yes') -%}
{%- set uses_db = uses_cockroachdb or uses_postgres or uses_mysql or uses_mongodb -%}

{%- set db_image = '' -%}
{%- set db_image = uses_cockroachdb and 'cockroachdb/cockroach' or db_image -%}
{%- set db_image = uses_postgres and 'postgres' or db_image -%}
{%- set db_image = uses_mysql and 'mysql' or db_image -%}
{%- set db_image = uses_mongodb and 'mongo' or db_image -%}

{%- set db_volume_path = '' -%}
{%- set db_volume_path = uses_cockroachdb and '/cockroach/cockroach-data' or db_volume_path -%}
{%- set db_volume_path = uses_postgres and '/var/lib/postgresql/data/' or db_volume_path -%}
{%- set db_volume_path = uses_mysql and '/var/lib/mysql' or db_volume_path -%}
{%- set db_volume_path = uses_mongodb and '/data/db' or db_volume_path -%}

networks:
  protected:
    driver: bridge
    internal: true
  connected:
    driver: bridge
    internal: true
  exposed:
    driver: bridge

volumes:
{%- if uses_db %}
  db-main-data:
    driver: local
{%- endif %}
  static-data:
    driver: local
  media-data:
    driver: local

services:
  app:
    build:
      context: ./{{ cookiecutter.app_path }}
    depends_on:
      {%- if uses_db %}
      - db-main
      {%- endif %}
      {%- if cookiecutter.use_redis in ["yes", "y"] %}
      - queue
      {%- endif %}
    env_file:
    - ./envfile
    networks:
    - protected
    - connected
    volumes:
    - media-data:/home/nonroot/code/media
{%- if uses_db %}
  db-main:
    networks:
    - protected
    image: {{ db_image }}
    volumes:
    - db-main-data:{{ db_volume_path }}
{%- endif %}
{%- if uses_redis %}
  queue:
    networks:
    - protected
    image: redis
    volumes:
    - redis-data:/data
{%- endif %}
  server:
    build:
      context: ./server
    depends_on:
    - app
    env_file:
    - ./envfile
    networks:
    - connected
    - exposed
    volumes:
    - static-data:/var/static
    - media-data:/var/media
